Repository codeblessing/json-tools, pull requests merged in 2022-01, with the labels that each got.

#44 Feature: Sort attributes alphabetically.
  json-tools.iml
  jsonTools.png
  pom.xml
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformSortFields.java
  src/main/java/pl/poznan/put/jsontools/rest/JsonToolsController.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformSortFieldsTest.java
Labels: enhancement, core

#45 Test/transform
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformFormat.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformFormatTest.java
Labels: tests

#48 change file
  JsonTools.png
  json-tools.png
  jsonTools.png
Labels: documentation

#55 complete documentation, add logging, correct formatting test
  src/main/java/pl/poznan/put/jsontools/app/JsonToolsApplication.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformCountFieldsValues.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformDeleteNulls.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformFlatten.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformFormat.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformMinify.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformRemoveAttributes.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformRetainAttributes.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformer.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonControllerTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformFlattenTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformRetainAttributesTest.java
Labels: documentation

#56 sprint 2 completed
  jsonTools.png
  pom.xml
  src/main/java/pl/poznan/put/jsontools/app/JsonToolsApplication.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformCountFieldsValues.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformDeleteNulls.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformFlatten.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformFormat.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformMinify.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformRemoveAttributes.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformRetainAttributes.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformService.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformSortFields.java
  src/main/java/pl/poznan/put/jsontools/logic/JsonTransformer.java
  src/main/java/pl/poznan/put/jsontools/rest/JsonToolsController.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonControllerTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformCountFieldsValuesTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformFlattenTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformFormatTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformRemoveAttributesTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformRetainAttributesTest.java
  src/test/java/pl/poznan/put/jsontools/logic/JsonTransformSortFieldsTest.java
Labels: important
